import { cva } from 'class-variance-authority';

export const sandboxSimpleCodeEditorStyles = cva([
  'relative',
  'text-left',
  'box-border',
  'p-0',
  'overflow-hidden',
  'flex-grow',
]);

export const sandboxSimpleCodeEditorTextareaStyles = cva([
  'py-0',
  'm-0',
  'border-none',
  '[background:none]',
  '[box-sizing:inherit]',
  '[display:inherit]',
  '[font-family:inherit]',
  '[font-size:inherit]',
  '[font-style:inherit]',
  '[font-variant-ligatures:inherit]',
  '[font-weight:inherit]',
  '[letter-spacing:inherit]',
  '[line-height:inherit]',
  '[tab-size:inherit]',
  '[text-indent:inherit]',
  '[text-rendering:inherit]',
  '[text-transform:inherit]',
  'whitespace-pre-wrap',
  'break-keep',
  '[overflow-wrap:break-word]',
  'empty:[-webkit-text-fill-color:inherit_!important]',
  'outline-none',
  'absolute',
  'z-[1]',
  'top-0',
  'left-0',
  'h-full',
  'w-full',
  'resize-none',
  '[color:inherit]',
  'overflow-hidden',
  '[-moz-osx-font-smoothing:grayscale]',
  '[-webkit-font-smoothing:antialiased]',
  '[-webkit-text-fill-color:transparent]',

  'pl-[var(--sandbox-editor-padding-left)]',
  'pr-[1.3125rem]',
  'caret-[color:var(--sandbox-editor-cursor-foreground)]',
  'selection:bg-[color:var(--sandbox-editor-selection-background)]',
]);

export const sandboxSimpleCodeEditorPreStyles = cva([
  'p-0',
  'm-0',
  'border-none',
  '[background:none]',
  '[box-sizing:inherit]',
  '[display:inherit]',
  '[font-family:inherit]',
  '[font-size:inherit]',
  '[font-style:inherit]',
  '[font-variant-ligatures:inherit]',
  '[font-weight:inherit]',
  '[letter-spacing:inherit]',
  '[line-height:inherit]',
  '[tab-size:inherit]',
  '[text-indent:inherit]',
  '[text-rendering:inherit]',
  '[text-transform:inherit]',
  'break-keep',
  '[overflow-wrap:break-word]',
  'relative',
  'pointer-events-none',

  'overflow-hidden',
  'whitespace-pre',
  'selection:bg-[color:var(--sandbox-editor-selection-background)]',
]);
